# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'afnworking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for afnworking

  target 'afnworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'afnworkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'

end
