# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BDwaimai' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BDwaimai

  target 'BDwaimaiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BDwaimaiUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
end
