# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TTBeautyRoll' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TTBeautyRoll

  target 'TTBeautyRollTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TTBeautyRollUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SDWebImage'
pod 'AFNetworking'
pod 'YYModel'
pod 'Masonry'
end
